### ISSUE TITLE
Target data before 2020?

### ISSUE THREAD

**Issue by ltsaprounis** [cdcepi/Flusight-forecast-data#1008]
Looking at the [data-truth](https://github.com/cdcepi/Flusight-forecast-data/tree/master/data-truth) section I only found data for the target variable `previous_day_admission_influenza_confirmed` from 2020 onwards. Is there any source containing the target for years prior to 2020?

For example I found data for outpatient visits dating all the way back to 2010 in the [fluview-dashboard](https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html) but couldn't find something similar for hospitalisations. 

Thanks in advance!

**Comment by rborchering** [comment]
Hello, there is historical data on hospitalizations available from FluSurv-Net https://www.cdc.gov/flu/weekly/influenza-hospitalization-surveillance.htm 
It is only available for select states and the data is in terms of weekly catchment population size-based rates, rather than the counts provided for previous day hospital admissions. Note that the catchment population size is based on the area covered by the FluSurv-Net network, as described in more detail in the link above.

**Comment by ltsaprounis** [comment]
Thanks @rborchering, thats a good source!
