### ISSUE TITLE
failed validation

### ISSUE THREAD

**Issue by tkcy** [cdcepi/Flusight-forecast-data#634]
Hi!
My [test submission](https://github.com/cdcepi/Flusight-forecast-data/pull/633) is failing validation - is it possible this is something on your end? Our file format should be unchanged from last year.
I'm happy to try again later in the week if that helps.
Thanks!
Teresa

**Comment by rborchering** [comment]
Hi Teresa, 
Thanks for submitting the test submission! It turns out that we needed to specify/update the python version in the yaml validation script. The validation still produces an error, but this one has to do with the date that the forecast is submitted and whether it is close to the forecast date. That check is close to the end of the validation script, so we'll be able to handle submissions with only that error. 
Thanks again!
Rebecca

**Comment by tkcy** [comment]
Great, thanks Rebecca!
